sudo: false
language: node_js
cache:
- directories:
  - node_modules
node_js:
- '0.10'
script: "npm run test"
env:
  global:
  - secure: "pS2bjSr5X1V0MTxB28JuX/rjeKsTSZgX9/DbO8nQ5vU0f36kXHn/JPUhBUHqrCb9g7MJd9ydDOZaqVKkz4BEM82tg3pRD5sbd7CkRO98nmfDQV/0eGyHGzzv8EhhvmNyTFWo8LuAt+IB/XLpLTDTF1dbPML0dQ1HQjf8njSVjY1WgTLNia0xl9cEyNWVyYll8LPFLidVZAKfyiUrcHN7q46ldadvNAmdSMqYdCNHQ4+WQB5ICSMJkIwAevrFPBuhmw1PGAHNmAp0MmC6+XVGjDZxA44Q6OCXon6Mct9Y2UPpcTNu4AJdnk/zuBhkhP/KfDmYeMvGRWt7rxCYzj90P7TkbOtVkC8FN8TYhWsb7xMr0ipjt0+rmzLioV1gS1Ep+He7Q4akH+Dpep1URbgmQEKVrgMXvsaUY0gf2weINlKTrZD4zSKBPdx6Y0g+dSRIi4e9wwuY6eYUpus/pmnP5Vu30IQQrI/Y3qnfKkdrFpmVpzkFyIdaDBycNn8n9+3+cFzHtZdSkwKmrZo+nYdqRNLECxzJotUjwU4orqyz4JlZCeRdSFgtjifOzH4xpon6ICISyoqLM2duPEzODAwjnQWWLXudSpTYJIcMDYYoE6tJmYphim+7uErT32NcDFCOYwEDtN65w76lJzmXxZOXeTYLp6E9T5+FX+uT7Nfm0Eg="
